# Generated by Django 3.0.6 on 2020-05-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(blank=True, max_length=254)),
                ('Contact_no', models.BigIntegerField(max_length=10)),
                ('Address', models.CharField(max_length=524)),
            ],
        ),
    ]
