# Generated by Django 3.0.6 on 2020-05-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bussinessapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Contact_no',
            field=models.PositiveSmallIntegerField(max_length=10),
        ),
    ]
