# Generated by Django 3.0.6 on 2020-05-10 11:24

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('Bussinessapp', '0002_auto_20200510_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='Contact_no',
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Address',
            field=models.CharField(help_text='Your Address', max_length=524),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Email',
            field=models.EmailField(blank=True, help_text='abc@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Name',
            field=models.CharField(help_text='Your GoodName', max_length=50),
        ),
    ]
